### ISSUE TITLE
Is this project still "mantained"?

### ISSUE THREAD

**Issue by bago** [brettstimmerman/mensch#19]
Hi Brett,

first of all I want to thank you for this great parser!

In the next weeks I'm going to publish an opensource project (https://github.com/voidlabs/mosaico) depending on my fork for mensch (https://github.com/bago/mensch).

As you can see (from other open issues and PR) I have applied a few patches to mensch, mainly related to "positions" and a few other improvements.

Is there any chance to get write access to your repository or to have you accept my PR anytime soon?

**Comment by brettstimmerman** [comment]
Hey @bago, I just returned from a month away and unplugged. I've added you as a collaborator. Thanks for offering to jump in!

**Comment by bago** [comment]
Thank you Brett! I just merged the PR and created a 0.3.2 release. Hope this is OK for you. Otherwise let me know so I fix it.
