### ISSUE TITLE
npm version publish request

### ISSUE THREAD

**Issue by maxwallasaurus** [brettstimmerman/mensch#22]
Hi @brettstimmerman and @bago,

I am using the npm package, juice, on a project for work. The Juice package has a dependency on mensch#v0.3.3, but they reference your github repository instead of the npm package itself. It looks like this could be because you haven't published the release to npm (currently 0.3.1 on npm). If it isn't too much of a hassle, would you mind publishing the latest release to npm? Then I can get them to switch the dependency to npm (my deployment setup doesn't allow me to use git on my prod server). 

Thanks for your time.
Cheers,
Max

**Comment by bago** [comment]
Unfortunately I only have access to this repository and not to the npm releases.

@brettstimmerman : would you mind sending me the password to make npm releases, too? Currently I can push releases here, but not in npm.

This has been asked here: #Automattic/juice/233

**Comment by maxwallasaurus** [comment]
Thanks @bago

**Comment by brettstimmerman** [comment]
@maxwallasaurus @bago Thanks for the heads up. I'm away from my personal computer, but I will add @bago to the npm owners later today.

**Comment by bago** [comment]
Hi Brett! my npm username is bago75
Thank you.

**Comment by brettstimmerman** [comment]
Apologies that took a little longer than I thought, but you're all set as an npm owner @bago!

**Comment by bago** [comment]
@brettstimmerman  Thank you! I'm new to "npm repository", but I guess I pushed 0.3.3.

In the mean time I also "registered" mensch to bower repository.

@maxwallasaurus Please ping me if anything is wrong, otherwise close this.

**Comment by maxwallasaurus** [comment]
Thanks guys! Really appreciate the help.

Cheers, 
Max
