### ISSUE TITLE
Please publish new version

### ISSUE THREAD

**Issue by jmtt89** [brettstimmerman/mensch#25]
Hi, 

version 0.3.3 has an error with stringify indentation, an error that has already been resolved about two years ago !!! but nobody has published a new version (0.3.4) with that solution

Can anyone publish that new version to fix that, please?

**Comment by brettstimmerman** [comment]
Hi @jmtt89! Thanks for the nudge. I hadn't realized things were behind.
I wonder if @bago is still interested in helping out?
If not, I'll publish the latest version soon. Thanks for being patient.

**Comment by brettstimmerman** [comment]
I just published v0.3.4 to npm. Enjoy!
